export const Icons = {
  profile: require('./icons/profile_j.jpg'),
  fitness_1: require('./icons/fitness.jpg'),
  muscle_1: require('./icons/muscle_2.jpg'),
  view1: require('./icons/view1.jpg'),
  view2: require('./icons/view2.jpg'),
  view3: require('./icons/view3.jpg'),
  logo: require('./icons/fitness360.png'),
  pushUp1: require('./icons/pushup1.jpg'),
  pressUp1: require('./icons/pressUp1.jpg'),
  male_avater: require('./icons/male_icon.jpg'),
  female_avater: require('./icons/famale_icon.jpg'),
  female_avater_1: require('./icons/female.jpg'),
  running1: require('./icons/running2.png'),
  nutrition1: require('./icons/nutrition2.png'),
  muscle4: require('./icons/muscle_4.jpg'),
  gym: require('./icons/gym1.png'),
  overweight: require('./icons/overweight.png'),
  obese1: require('./icons/obese1.png'),
  skinny: require('./icons/skinny1.png'),
  normal_weight: require('./icons/normal1.png'),
};
