export const Icons = {
  profile: require('./icons/profile_j.jpg'),
  fitness_1: require('./icons/fitness.jpg'),
  muscle_1: require('./icons/muscle_2.jpg'),
  view1: require('./icons/view1.jpg'),
  view2: require('./icons/view2.jpg'),
  view3: require('./icons/view3.jpg'),
  logo: require('./icons/fitness360.png'),
  pushUp1: require('./icons/pushup1.jpg'),
  pressUp1: require('./icons/pressUp1.jpg'),
  male_avater: require('./icons/male_icon.jpg'),
  female_avater: require('./icons/famale_icon.jpg'),
  female_avater_1: require('./icons/female.jpg'),
  running1: require('./icons/running2.png'),
  nutrition1: require('./icons/nutrition2.png'),
  muscle4: require('./icons/muscle_4.jpg'),
  gym: require('./icons/gym1.png'),
  overweight: require('./icons/overweight.png'),
  obese1: require('./icons/obese1.png'),
  skinny: require('./icons/skinny1.png'),
  normal_weight: require('./icons/normal1.png'),
  normal_body: require('./icons/normal_body.png'),
  skinny_1: require('./icons/skinny_3.png'),
  bulk_1: require('./icons/bulk.png'),
  cut: require('./icons/body_cut.png'),
  muscular_body: require('./icons/musclar.png'),
  bodyZone: require('./icons/bodyzones.png'),
  bad_habit: require('./icons/bad_habits.png'),
  terms_aggreement: require('./icons/term-aggreement-preview.png'),
  plan_1: require('./icons/plan_1.png'),
  plan_2: require('./icons/plan_2.png'),
  card_background: require('./icons/card_background.jpg'),
  clock: require('./icons/clock.png'),
  play: require('./icons/play.png'),
  calender: require('./icons/calender.png'),
  congrats: require('./icons/congrats.png'),
  figure_count_down: require('./icons/figure_count_down.gif'),
};

// instructions assets

export const CardIcons = {
  female: {
    back: require('./icons/cards/female/back.png'),
    belly: require('./icons/cards/female/belly.png'),
    biceps: require('./icons/cards/female/biceps.png'),
    forearms: require('./icons/cards/female/forearms.png'),
    legs: require('./icons/cards/female/legs.png'),
    neck: require('./icons/cards/female/neck.png'),
    thighs: require('./icons/cards/female/thights.png'),
    triceps: require('./icons/cards/female/triceps.png'),
    pecs: require('./icons/cards/male/pecs.png'),
    shoulder: require('./icons/cards/male/shoulder.png'),
    skinny: require('./icons/cards/female/skinny.png'),
  },
  male: {
    back: require('./icons/cards/male/back.png'),
    belly: require('./icons/cards/male/belly.png'),
    biceps: require('./icons/cards/male/biceps.png'),
    chest: require('./icons/cards/male/chest.png'),
    forearms: require('./icons/cards/male/forearms.png'),
    legs: require('./icons/cards/male/leg.png'),
    neck: require('./icons/cards/male/neck.png'),
    pecs: require('./icons/cards/male/pecs.png'),
    shoulder: require('./icons/cards/male/shoulder.png'),
    triceps: require('./icons/cards/male/triceps.png'),
    thighs: require('./icons/cards/female/thights.png'),
    skinny: require('./icons/cards/male/skinny.png'),
  },
  tools: [
    require('@assets/icons/cards/tool/tool_1.png'),
    require('@assets/icons/cards/tool/tool_2.png'),
    require('@assets/icons/cards/tool/tool_3.png'),
    require('@assets/icons/cards/tool/tool_4.png'),
    require('@assets/icons/cards/tool/tool_5.png'),
  ],
};
export function getToolImg() {
  const randomIndex = Math.floor(Math.random() * CardIcons.tools.length);
  return CardIcons.tools[randomIndex];
}
export const bodyZones = {
  skinny: {
    female: {
      burpees1: require('@assets/icons/skinny/female/burpees1v2.gif'),
      burpees2: require('@assets/icons/skinny/female/burpees2v2.gif'),
      burpees3: require('@assets/icons/skinny/female/burpees3v2.gif'),
      burpees4: require('@assets/icons/skinny/female/burpees4v2.gif'),
      burpees5: require('@assets/icons/skinny/female/burpees6.gif'),
      burpees6: require('@assets/icons/skinny/female/burpees7.gif'),
      burpees7: require('@assets/icons/skinny/female/burpees8.gif'),
      burpees8: require('@assets/icons/skinny/female/burpees9.gif'),
      high_knee_jacks: require('@assets/icons/skinny/female/high_knee_jacks.gif'),
      high_plank_hold: require('@assets/icons/skinny/female/high-plank-hold.webp'),
      hollow_rock: require('@assets/icons/skinny/female/hollow-rock.gif'),
      inchworm: require('@assets/icons/skinny/female/inchworm.gif'),
      knee_Push_ups: require('@assets/icons/skinny/female/knee_Push_ups.gif'),
      leg_drops: require('@assets/icons/skinny/female/leg_drops.gif'),
      Mountain_Climbers1: require('@assets/icons/skinny/female/Mountain_Climbers-1.webp'),
      plank1: require('@assets/icons/skinny/female/plank1.gif'),
      ReversePlank: require('@assets/icons/skinny/female/ReversePlank.gif'),
      SliderClimbers: require('@assets/icons/skinny/female/SliderClimbers.gif'),
      star_jump: require('@assets/icons/skinny/female/star-jump.gif'),
      squat_hold: require('@assets/icons/skinny/female/squat-hold.webp'),
      StraightArmPlank: require('@assets/icons/skinny/female/StraightArmPlank.gif'),
      superman: require('@assets/icons/skinny/female/superman.gif'),
      sworkit_jumping_jack: require('@assets/icons/skinny/female/sworkit-jumping-jack.webp'),
    },
    male: {
      arm_circles: require('@assets/icons/skinny/male/arm_circles.gif'),
      front_squat: require('@assets/icons/skinny/male/front-squat.gif'),
      jumping_jacks: require('@assets/icons/skinny/male/jumping-jacks.gif'),
      highkneerun: require('@assets/icons/skinny/male/highkneerun.gif'),
      jumping: require('@assets/icons/skinny/male/jumping.gif'),
      knee_Push_ups: require('@assets/icons/skinny/male/knee_Push_ups.gif'),
      knee_tuck_crunch: require('@assets/icons/skinny/male/knee_tuck_crunch.gif'),
      legs_drop_2: require('@assets/icons/skinny/male/legs_drop_2.gif'),
      m_leg_drops: require('@assets/icons/skinny/male/m_leg_drops.gif'),
      mountain_climbers: require('@assets/icons/skinny/male/Mountain-climbers.gif'),
      mountain_climbers2: require('@assets/icons/skinny/male/mountain-Climbers.gif'),
      mountainclimber: require('@assets/icons/skinny/male/Mountain-climbers.gif'),
      Plank_Jack_Burpees: require('@assets/icons/skinny/male/Plank-Jack-Burpees.gif'),
      plank1: require('@assets/icons/skinny/male/plank.gif'),
      reverse_crunches: require('@assets/icons/skinny/male/reverse_crunches.gif'),
      running_in_place: require('@assets/icons/skinny/male/Running-In-Place.gif'),
      Step_Back_Jacks_with_Knee_Tuck: require('@assets/icons/skinny/male/Step-Back-Jacks-with-Knee-Tuck.gif'),
      superman1: require('@assets/icons/skinny/male/Superman1.gif'),
      superman_2: require('@assets/icons/skinny/male/superman_2.gif'),
    },
  },
  back: {
    female: {
      Back_Moves_for_a_Stronger_Back_Barbell: require('@assets/icons/zones/back/female/Back_Moves_for_a_Stronger_Back_Barbell.webp'),
      Back_Moves_for_a_Stronger_Back_Resistance_Band_Pull_Aparts: require('@assets/icons/zones/back/female/Back_Moves_for_a_Stronger_Back_Resistance_Band_Pull_Aparts.webp'),
      Back_Moves_for_a_Stronger_Back_Single_Arm_Dumbbell_Row_off_Bench: require('@assets/icons/zones/back/female/Back_Moves_for_a_Stronger_Back_Single_Arm_Dumbbell_Row_off_Bench.webp'),
      Back_Woodchop_with_Medicine_Ball: require('@assets/icons/zones/back/female/Back_Woodchop_with_Medicine_Ball.webp'),
      BarbellDeadlift: require('@assets/icons/zones/back/female/BarbellDeadlift.webp'),
      cat_cow_in_pink_top: require('@assets/icons/zones/back/female/cat-cow-in-pink-top.webp'),
      Dumbbell_pullover: require('@assets/icons/zones/back/female/Dumbbell-pullover.webp'),
      Low_Weight_and_High_Reps_Seated_Lat_Pull_Down: require('@assets/icons/zones/back/female/Low_Weight_and_High_Reps_Seated_Lat_Pull_Down.webp'),
      Reverse_Fly_with_Dumbbells: require('@assets/icons/zones/back/female/Posture_While_Breastfeeding_Actually_Matters_Bent_Over_Reverse_Fly_with_Dumbbells-1.webp'),
      Suit_Your_Needs_Bent_Over_Row: require('@assets/icons/zones/back/female/Suit_Your_Needs_Bent_Over_Row.webp'),
    },
    male: {
      Posture_Superman: require('@assets/icons/zones/back/male/Back_Exercises_With_Bands_to_Counteract_Work_From_Home_Posture_Superman.webp'),
      SmithMachineRows: require('@assets/icons/zones/back/male/HL-02.01.SmithMachineRows.webp'),
      DumbbellPull_Over: require('@assets/icons/zones/back/male/HL-02.04.DumbbellPull-Over.webp'),
    },
  },
  belly: {
    female: {
      Exercises_for_Washboard_Abs_Flat_Bench_Leg_Raise: require('@assets/icons/zones/belly/female/400x400_6_Exercises_for_Washboard_Abs_Flat_Bench_Leg_Raise.gif'),
      Exercises_for_Washboard_Abs_Flutter_Kicks: require('@assets/icons/zones/belly/female/400x400_6_Exercises_for_Washboard_Abs_Flutter_Kicks.gif'),
      Exercises_for_Washboard_Abs_Toe_Reach: require('@assets/icons/zones/belly/female/400x400_6_Exercises_for_Washboard_Abs_Toe_Reach.gif'),
      Exercises_That_Help_You_Get_V_Reverse_Crunches: require('@assets/icons/zones/belly/female/400x400_Exercises_That_Help_You_Get_V_Reverse_Crunches-2.gif'),
      Exercises_to_Make_the_Most_of_Your_Oblique_Workout_Bicycle_Crunch: require('@assets/icons/zones/belly/female/400x400_Exercises_to_Make_the_Most_of_Your_Oblique_Workout_Bicycle_Crunch-3.gif'),
      Exercises_to_Make_the_Most_of_Your_Oblique_Workout_Side_Plank: require('@assets/icons/zones/belly/female/400x400_Exercises_to_Make_the_Most_of_Your_Oblique_Workout_Side_Plank.webp'),
      ScissorKicks: require('@assets/icons/zones/belly/female/HL-01.07.ScissorKicks.gif'),
    },
    male: {
      How_to_Do_a_Russian_Twist_and_Strengthen_Your_Core_Legs_Crossed: require('@assets/icons/zones/belly/male/400x400_How_to_Do_a_Russian_Twist_and_Strengthen_Your_Core_Legs_Crossed.gif'),
      AbContractions: require('@assets/icons/zones/belly/male/HL-01.01.AbContractions.gif'),
      LegDrops: require('@assets/icons/zones/belly/male/HL-01.02.LegDrops.gif'),
      HipLift: require('@assets/icons/zones/belly/male/HL-01.03.HipLift.gif'),
      BoatPose: require('@assets/icons/zones/belly/male/HL-01.04.BoatPose.gif'),
      MountainClimbers: require('@assets/icons/zones/belly/male/HL-01.05.MountainClimbers.webp'),
      RockingPlank: require('@assets/icons/zones/belly/male/HL-01.06.RockingPlank.gif'),
      TheHundred: require('@assets/icons/zones/belly/male/HL-01.08.TheHundred.gif'),
      BicycleCrunches: require('@assets/icons/zones/belly/male/HL-01.09.BicycleCrunches.gif'),
    },
  },
  biceps: {
    female: {
      Denise_Wide_Grip_20Biceps_20Curl: require('@assets/icons/zones/biceps/female/Denise_Wide_Grip_20Biceps_20Curl.gif'),
      dumbbell_single_arm_bicep_curl: require('@assets/icons/zones/biceps/female/dumbbell-single-arm-bicep-curl-Cookie_055.gif'),
      Francine_arnold_press: require('@assets/icons/zones/biceps/female/Francine-arnold-press.gif'),
      Francine_bent_over_row: require('@assets/icons/zones/biceps/female/Francine_bent-over-row.gif'),
      Jo_chest_press: require('@assets/icons/zones/biceps/female/Jo-chest-press.gif'),
      lateral_raise_to_front_raise_rachel: require('@assets/icons/zones/biceps/female/lateral-raise-to-front-raise-rachel.gif'),
      skull_crusher_Rachel: require('@assets/icons/zones/biceps/female/skull-crusher-Rachel_042.gif'),
      three_point_row: require('@assets/icons/zones/biceps/female/three_point_row.gif'),
      Wide_Lifted_Bicep_Curl: require('@assets/icons/zones/biceps/female/Wide_Lifted_Bicep_Curl.webp'),
    },
    male: {
      Concentration_Curl: require('@assets/icons/zones/biceps/male/_Concentration_Curl.gif'),
      Barbell_Bicep_Curl: require('@assets/icons/zones/biceps/male/Barbell_Bicep_Curl.gif'),
      Leant_Forward_EZ_Bar_Curl: require('@assets/icons/zones/biceps/male/Leant_Forward_EZ_Bar_Curl.gif'),
      Prone_Dumbbell_Spider_Curl: require('@assets/icons/zones/biceps/male/Prone_Dumbbell_Spider_Curl.gif'),
      Reverse_Grip_EZ_Bar_Curl: require('@assets/icons/zones/biceps/male/Reverse-Grip_EZ Bar_Curl.gif'),
      reversecurl: require('@assets/icons/zones/biceps/male/reversecurlgif.gif'),
      Twisting_Dumbbell_Curl: require('@assets/icons/zones/biceps/male/Twisting_Dumbbell_Curl.gif'),
    },
  },
  forearms: {
    female: {
      tricep_dips: require('@assets/icons/zones/forearms/female/1-tricep-dips-4e241b5bde4b47b59b6801a99583dcd3.gif'),
      Inner_Wrist_Curls: require('@assets/icons/zones/forearms/female/Inner_Wrist_Curls.webp'),
    },
    male: {
      Exercises_to_Do_at_the_Gym_or_at_Home_Grip_Crush: require('@assets/icons/zones/forearms/male/400x400_Forearm-Exercises_to_Do_at_the_Gym_or_at_Home_Grip_Crush.webp'),
      bent_over_row: require('@assets/icons/zones/forearms/male/bent-over-row-1590133418.jpg'),
      big_arms_2: require('@assets/icons/zones/forearms/male/big-arms_2.webp'),
      big_arms_3: require('@assets/icons/zones/forearms/male/big-arms_3.webp'),
      big_arms: require('@assets/icons/zones/forearms/male/big_arms.webp'),
      Crab_Walks: require('@assets/icons/zones/forearms/male/Crab-Walks.gif'),
      curlszottman: require('@assets/icons/zones/forearms/male/curlszottman.gif'),
      Forearm_Twist: require('@assets/icons/zones/forearms/male/Forearm-Twist.webp'),
      hammer_url: require('@assets/icons/zones/forearms/male/hammer-curl.gif'),
      HAMMER_CURL_TO_PAUSE_TWIST_AND_SUPINATED_LOWER: require('@assets/icons/zones/forearms/male/HAMMER_CURL_TO_PAUSE_TWIST_AND_SUPINATED_LOWER.webp'),
      how_to_do_a_lateral_raise: require('@assets/icons/zones/forearms/male/how-to-do-a-lateral-raise.gif'),
      INCLINE_BENCH_ZOTTMAN_CURL: require('@assets/icons/zones/forearms/male/INCLINE_BENCH_ZOTTMAN_CURL.webp'),
      LinearNaughtyGar: require('@assets/icons/zones/forearms/male/LinearNaughtyGar-size_restricted.gif'),
      palmsupwristcurl: require('@assets/icons/zones/forearms/male/palmsupwristcurl.gif'),
      Rear_Roasters: require('@assets/icons/zones/forearms/male/Rear_Roasters.webp'),
      tricep_extension: require('@assets/icons/zones/forearms/male/tricep-extension-1575474664.gif'),
      Wrist_Curl: require('@assets/icons/zones/forearms/male/Wrist-Curl.webp'),
    },
  },
  legs: {
    female: {
      burpees: require('@assets/icons/zones/legs/female/burpees.gif'),
      Glute_Bridge: require('@assets/icons/zones/legs/female/Glute_Bridge.webp'),
      Hold_the_top_of_a_dumbbell: require('@assets/icons/zones/legs/female/Hold_the_top_of_a_dumbbell.webp'),
      Laying_down: require('@assets/icons/zones/legs/female//Laying_down.webp'),
      Lean_Leg_Workout_cove: require('@assets/icons/zones/legs/female/Lean-Leg-Workout-cover.gif'),
    },
    male: {
      DB_Deadlifts: require('@assets/icons/zones/legs/male/DB_Deadlifts.webp'),
      Single_Leg_Reverse_Lunge: require('@assets/icons/zones/legs/male/Single_Leg_Reverse_Lunge.webp'),
    },
  },
  neck: {
    female: {
      Superman: require('@assets/icons/zones/neck/female/400x400-Superman.webp'),
      head_turns: require('@assets/icons/zones/neck/female/a-gif-of-head-turns.gif'),
      neck_rotate: require('@assets/icons/zones/neck/female/neck_rotate.gif'),
      CHIN_TUCK_: require('@assets/icons/zones/neck/female/CHIN-TUCK_1296x729.gif'),
      SIDE_TO_SIDE_TURNS: require('@assets/icons/zones/neck/female/SIDE-TO-SIDE-TURNS_1296x729.gif'),
    },
    male: {
      neck_1: require('@assets/icons/zones/neck/male/1600935628_620700.gif'),
      stiff_neck: require('@assets/icons/zones/neck/male/stiff_neck.webp'),
    },
  },
  pecs: {
    male: {
      cablefly: require('@assets/icons/zones/pecs/male/cablefly.gif'),
      decline_push_up: require('@assets/icons/zones/pecs/male/decline-push-up.gif'),
      DeclineB: require('@assets/icons/zones/pecs/male/DeclineB.gif'),
      staggered_press_up: require('@assets/icons/zones/pecs/male/how-to-do-a-staggered-press-up.gif'),
      close_grip_bench_press: require('@assets/icons/zones/pecs/male/how-to-do-the-close-grip-bench-press.gif'),
      incline_bench_press: require('@assets/icons/zones/pecs/male/incline-bench-press.gif'),
      inclinedumbbellpress: require('@assets/icons/zones/pecs/male/inclinedumbbellpress.gif'),
      neutralgripchestpress: require('@assets/icons/zones/pecs/male/neutralgripchestpress.gif'),
      Pump_Up_Your_Pecs: require('@assets/icons/zones/pecs/male/Pump_Up_Your_Pecs.gif'),
      push_up: require('@assets/icons/zones/pecs/male/push-up-variations-600-t-push-up.gif'),
      slowclap: require('@assets/icons/zones/pecs/male/slowclap.gif'),
      wide_push_up1: require('@assets/icons/zones/pecs/male/wide-push-up1.gif'),
    },
  },
  shoulder: {
    male: {
      dumbell_1: require('@assets/icons/zones/shoulder/02.gif'),
      broad_shoulders: require('@assets/icons/zones/shoulder/broad_shoulders.webp'),
      check: require('@assets/icons/zones/shoulder/check.gif'),
      dumbbellshoulderpress: require('@assets/icons/zones/shoulder/dumbbellshoulderpress.webp'),
      overheadpress_jj: require('@assets/icons/zones/shoulder/overheadpress_jj.gif'),
      Back_Moves_for_a_Stronger_Back_Barbell: require('@assets/icons/zones/shoulder/Pushups.webp'),
    },
  },
  thighs: {
    female: {
      Hamstring_curl_with_a_ball: require('@assets/icons/zones/thighs/female/Hamstring-curl-with-a-ball.webp'),
      Hamstring_curl_dumbbell: require('@assets/icons/zones/thighs/female/Hamstring-curl-with-a-dumbbell.webp'),
      Prone_hamstring_curl: require('@assets/icons/zones/thighs/female/Prone-hamstring-curl.webp'),
      Seated_hamstring_curl: require('@assets/icons/zones/thighs/female/Seated-hamstring-curl.webp'),
      Standing_hamstring_curl: require('@assets/icons/zones/thighs/female/Standing-hamstring-curl.webp'),
    },
  },
  triceps: {
    female: {
      dumbbell_bent_over_triceps_kick: require('@assets/icons/zones/triceps/female/dumbbell-bent-over-triceps-kick-back.gif'),
      HonoredFamousIbex_size_restricted: require('@assets/icons/zones/triceps/female/HonoredFamousIbex-size_restricted.webp'),
      TricepOverhead: require('@assets/icons/zones/triceps/female/TricepOverhead.gif'),
    },
    male: {
      barbelltricepsextension: require('@assets/icons/zones/triceps/male/barbelltricepsextension.gif'),
      diamond: require('@assets/icons/zones/triceps/male/diamond-1589888104.jpg'),
      diamond_press_up: require('@assets/icons/zones/triceps/male/diamond-press-up.gif'),
      floor_press: require('@assets/icons/zones/triceps/male/floor-press-1586948016.jpg'),
      close_grip_bench_press: require('@assets/icons/zones/triceps/male/how-to-do-the-close-grip-bench-press.gif'),
      single_arm_dumbbell_tricep_extension: require('@assets/icons/zones/triceps/male/how-to-do-the-single-arm-dumbbell-tricep-extension.gif'),
      Javelin_Press: require('@assets/icons/zones/triceps/male/Javelin_Press.gif'),
      kettlebell_floor: require('@assets/icons/zones/triceps/male/kettlebell-floor.gif'),
      pressup: require('@assets/icons/zones/triceps/male/pressup-1601994364.jpg'),
      skullcrushergif: require('@assets/icons/zones/triceps/male/skullcrushergif.gif'),
      Tate_Press: require('@assets/icons/zones/triceps/male/Tate_Press.gif'),
      tricep_bulking: require('@assets/icons/zones/triceps/male/tricep-bulking.gif'),
    },
  },
};
